server: # REST and WS server
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 1
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
  plugins:
    - dependency: "com.github.esmBot:lava-xm-plugin:v0.2.1"
      repository: "https://jitpack.io"
    - dependency: "com.github.TopiSenpai.LavaSrc:lavasrc-plugin:3.2.0"
      repository: "https://jitpack.io"

plugins:
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: false
      applemusic: true
      deezer: false
    spotify:
        clientId: "your client id"
        clientSecret: "your client secret"
        countryCode: "US"
    applemusic:
        countryCode: "US"
    deezer:
        masterDecryptionKey: "go looking for this somewhere"

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO

