name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
        version: 9.4.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
      with:
        node-version: 20
        cache: pnpm
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake libvips-dev libmagick++-dev libzxingcore-dev
    - name: Build
      run: pnpm install --frozen-lockfile --no-optional && pnpm run build

  darwin:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
        version: 9.4.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
      with:
        node-version: 20
        cache: pnpm
    - name: Install dependencies
      run: brew install imagemagick vips python-setuptools # https://github.com/nodejs/node-gyp/issues/2869
    - name: Build
      run: pnpm install --frozen-lockfile --no-optional && pnpm run build --CDWITH_ZXING=OFF

